# Generated by Django 4.1.7 on 2023-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='contents')),
                ('metadata', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='channels')),
                ('contents', models.ManyToManyField(blank=True, related_name='channels', to='core.content')),
                ('subchannels', models.ManyToManyField(blank=True, related_name='parent_channels', to='core.channel')),
            ],
        ),
    ]
