# Generated by Django 4.1.7 on 2023-03-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contents')),
                ('metadata', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
